@url=http://localhost:3000

### POST para calcular perímetro y superficie del rectángulo
POST {{url}}/calculos
Content-Type: application/json

{
  "base": 10,
  "altura": 10
}

### GET para obtener los datos de los cálculos realizados
GET {{url}}/calculos