@url=http://localhost:3000

### POST - para crear un alumno
POST {{url}}/alumnos
Content-Type: application/json

{
    "nombre": "Nicolas Vazquez",
    "notas": [8, 7.5, 9]
}

### GET - para obtener el listado de alumnos
GET {{url}}/alumnos

### GET - para obtener un solo alumno (colocar %20 entre nombre y apellido del alumno)
GET {{url}}/alumnos/Nicolas%20Vazquez