@url=http://localhost:3000

### POST para crear una tarea nueva
POST {{url}}/creartarea
Content-Type: application/json

{
    "nombre": "tarea5",
    "estado": "incompleta"
}

### GET para ver todas las tareas
GET {{url}}/tareas

### GET para ver tarea segun estado (completa / incompleta)
GET {{url}}/tareas/incompleta